name = "Ham on Ray Games"
description = ""
keywords = "ham on ray, games, game studio, blender, youtube"
image = ""
theme = "dark"
primary_color = "#c93529"
text_align = "center"
gtag_id = ""
base_url = "https://hamonraygames.github.io"

[[sections]]
title = "Links"
description = "Look for us there"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Youtube"
url = "https://www.youtube.com/@hamonraygames"
